# vim: ts=2:sts=2:sw=2:expandtab:smarttab:
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.17
    commands:
      - go build -o build/server cmd/server/main.go

  - name: fenek-release
    image: registry.wachanga.com/drone/fenek-release
    when:
      event: tag

  - name: publish-dev
    image: plugins/docker
    when:
      branch: develop
      event:
        exclude:
          - pull_request
    settings:
      repo: registry.wachanga.com/backend/outpost
      registry: registry.wachanga.com
      tag:
        - develop
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish
    image: plugins/docker
    when:
      event: tag
    settings:
      repo: registry.wachanga.com/backend/outpost
      registry: registry.wachanga.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest
        - ${DRONE_TAG}
