http:
  port: 8080

auth:
  title: some_service
  icon: https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/c1/3d/a5/c13da51a-5152-29d3-b668-4547e8873cc6/mzl.nhnzrmvu.png/230x0w.jpg
  access_cookie_name: auth_token # must match the name of the backend-auth cookie
  refresh_cookie_name: refresh_token # must match the name of the backend-auth cookie
  cookie_domain: "wachanga.com" # must match the name of the backend-auth cookie's domain field
  oauth_url: https://auth.wachanga.com/api/1.0/oauth/github
  
auth_headers:
  enabled: true
  headers:
    # property: header_name
    login: "X-WACHANGA-WEBAUTH-USER"
    email: "X-WACHANGA-WEBAUTH-EMAIL"

proxy:
  target: http://hello-world:80
  host: hello-world

log:
  # Available formats: json, plain
  format: plain

jwt:
  sign_key: some_secret_sign_key
  iss: https://auth.wachanga.com
  aud: oauth_github
  refresh_token_ttl: 1440h  # 2 * 30 * 24 hours (2 month)
  worker_delay: 10s

resty:
  retry_count: 5
  retry_wait_time: 10s
  timeout: 30s

mysql:
  host: mysql
  port: 3306
  user: root
  password: pass
  database: outpost

auth_api:
  host: "https://auth.wachanga.com"
